import { NonLinkableSegment } from "@/types/quizType";

/**
 * Represents a string used for selecting all categories in filtering.
 */
export const ALL_CATEGORY = "all";

/**
 * A map that converts Katakana characters to their respective numeric values.
 *
 * @remarks
 * This map is not declared as a constant because maps cannot be declared as strict constants.
 *
 * - "ア" maps to 0
 * - "イ" maps to 1
 * - "ウ" maps to 2
 * - "エ" maps to 3
 * - "オ" maps to 4
 */
export const katakanaToNumbersMap = new Map<string, number>([
  ["ア", 0],
  ["イ", 1],
  ["ウ", 2],
  ["エ", 3],
  ["オ", 4],
]);

/**
 * A reverse map that converts numeric values to their respective Katakana characters.
 *
 * @remarks
 * This map is generated by reversing `katakanaToNumbersMap`.
 */
export const numberToKatakanaMap = new Map<number, string>(
  Array.from(katakanaToNumbersMap, ([katakana, number]) => [number, katakana]),
);

/**
 * An array of non-linkable segments specifically used in quiz URLs.
 *
 * @remarks
 * - The label "quiz" corresponds to the first part of the URL.
 */
export const nonLinkableSegmentsByQuiz = [
  { label: "quiz", index: 0 } as NonLinkableSegment, // 'quiz' is the first part of the URL
];

/**
 * An array of non-linkable segments specifically used in admin URLs.
 *
 * @remarks
 * - The label "edit" corresponds to the fifth part of the URL.
 */
export const nonLinkableSegmentsByAdmin = [
  { label: "edit", index: 4 } as NonLinkableSegment, // 'edit' is the fifth part of the URL
];

/**
 * The caching duration for fetch operations, set to 31 days (in seconds).
 *
 * @remarks
 * This value assumes that cache invalidation will primarily be handled using `revalidateTag()`.
 */
export const FETCH_REVALIDATE = 2678400;
